; =================================================================================================
; POINTER TABLE DATA: DIALOGUES
; origin: $1DD94
; Format: XX.b YYYY.w
;         XX:   Textbox Type
;         YYYY: Distance from pointer table base
; =================================================================================================
    
    align 2

base_PointerTable_Dialogues:
    dc.b $00
    dc.w text1-base_PointerTable_Dialogues
    dc.b $01
    dc.w text2-base_PointerTable_Dialogues
    dc.b $00
    dc.w text3-base_PointerTable_Dialogues
    dc.b $01
    dc.w text4-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text5-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text6-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text7-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text8-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text9-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text10-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text11-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text12-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text13-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text14-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text15-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text16-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text17-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text18-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text19-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text20-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text21-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text22-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text23-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text24-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text25-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text26-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text27-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text28-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text29-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text30-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text31-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text32-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text33-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text34-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text35-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text36-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text37-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text38-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text39-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text40-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text41-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text42-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text43-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text44-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text45-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text46-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text47-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text48-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text49-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text50-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text51-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text52-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text53-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text54-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text55-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text56-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text57-base_PointerTable_Dialogues 
    dc.b $02
    dc.w text58-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text59-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text60-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text61-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text62-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text63-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text64-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text65-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text66-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text67-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text68-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text69-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text70-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text71-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text72-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text73-base_PointerTable_Dialogues 
    dc.b $05
    dc.w text74-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text75-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text76-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text77-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text78-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text79-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text80-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text81-base_PointerTable_Dialogues 
    dc.b $03
    dc.w text82-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text83-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text84-base_PointerTable_Dialogues 
    dc.b $03
    dc.w text85-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text86-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text87-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text88-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text89-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text90-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text91-base_PointerTable_Dialogues 
    dc.b $04
    dc.w text92-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text93-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text94-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text95-base_PointerTable_Dialogues 
    dc.b $03
    dc.w text96-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text97-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text98-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text99-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text100-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text101-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text102-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text103-base_PointerTable_Dialogues 
    dc.b $03
    dc.w text104-base_PointerTable_Dialogues 
    dc.b $03
    dc.w text105-base_PointerTable_Dialogues 
    dc.b $07
    dc.w text106-base_PointerTable_Dialogues 
    dc.b $07
    dc.w text107-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text108-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text109-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text110-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text111-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text112-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text113-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text114-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text115-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text116-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text117-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text118-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text119-base_PointerTable_Dialogues 
    dc.b $03
    dc.w text120-base_PointerTable_Dialogues 
    dc.b $07
    dc.w text121-base_PointerTable_Dialogues 
    dc.b $00
    dc.w text122-base_PointerTable_Dialogues 
    dc.b $06
    dc.w text123-base_PointerTable_Dialogues 
    dc.b $06
    dc.w text124-base_PointerTable_Dialogues 
    dc.b $06
    dc.w text125-base_PointerTable_Dialogues 
    dc.b $06
    dc.w text126-base_PointerTable_Dialogues 
    dc.b $06
    dc.w text127-base_PointerTable_Dialogues 
    dc.b $06
    dc.w text128-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text129-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text130-base_PointerTable_Dialogues 
    dc.b $01
    dc.w text131-base_PointerTable_Dialogues
